# Generated by Django 3.0.5 on 2020-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilLinkedin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_linkedin_admin_id', models.CharField(blank=True, max_length=100)),
                ('linkedin_id', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('photo', models.URLField(blank=True)),
                ('r_liteprofile', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'ProfilLinkedin',
            },
        ),
        migrations.CreateModel(
            name='ProfilLinkedinAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_id', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('photo', models.URLField(blank=True)),
                ('r_liteprofile', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'ProfilLinkedinAdmin',
            },
        ),
    ]
