# Generated by Django 3.0.5 on 2020-04-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storiesof', '0003_auto_20200414_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
