# Generated by Django 3.0.5 on 2020-04-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storiesof', '0004_project_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profillinkedin',
            name='profil_linkedin_admin_id',
        ),
        migrations.AddField(
            model_name='profillinkedin',
            name='project_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storiesof.Project'),
            preserve_default=False,
        ),
    ]
