# Generated by Django 3.0.5 on 2020-04-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storiesof', '0005_auto_20200414_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='photo_url',
        ),
    ]
