# Generated by Django 3.0.5 on 2020-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storiesof', '0006_auto_20200414_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profillinkedin',
            name='photo',
            field=models.ImageField(upload_to='asset/img/profiles'),
        ),
    ]
