# Generated by Django 3.0.5 on 2020-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storiesof', '0007_auto_20200416_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profillinkedin',
            name='photo',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
