# Generated by Django 3.0.5 on 2020-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storiesof', '0008_auto_20200416_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profillinkedin',
            name='photo_static',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
