# Generated by Django 3.0.5 on 2020-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storiesof', '0009_profillinkedin_photo_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profillinkedin',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
