# Generated by Django 3.0.5 on 2020-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storiesof', '0010_auto_20200416_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profillinkedin',
            name='photo_report',
            field=models.URLField(blank=True),
        ),
    ]
